coverage:
  range: 60..80
  round: down
  precision: 2
  status:
    project:
      default:
        target: 70
        threshold: 5
        base: auto
    patch:
      default:
        target: 70
        threshold: 5
        base: auto
